### ISSUE TITLE
ERROR in ch.qos.logback.core.joran.spi.Interpreter@XX:XX - no applicable action for [maxBatchSize], current ElementPath  is [[configuration][appender][maxBatchSize]]

### ISSUE THREAD

**Issue by mrsarm** [pierredavidbelanger/logback-awslogs-appender#11]
When I try to add any of these configurations `maxBatchSize`, `maxFlushTimeMillis`, `maxBlockTimeMillis` to the `AwsLogsAppender` appender, I get this error and the application is stopped:

```
Logging system failed to initialize using configuration from 'classpath:logback.xml'
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.spi.Interpreter@14:23 - no applicable action for [maxBatchSize], current ElementPath  is [[configuration][appender][maxBatchSize]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@15:29 - no applicable action for [maxFlushTimeMillis], current ElementPath  is [[configuration][appender][maxFlushTimeMillis]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@16:29 - no applicable action for [maxBlockTimeMillis], current ElementPath  is [[configuration][appender][maxBlockTimeMillis]]
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:153)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithSpecificConfig(AbstractLoggingSystem.java:56)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:46)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:106)
	at org.springframework.boot.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:267)
	at org.springframework.boot.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:233)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:200)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:65)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:325)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at com.garbarino.api.checkout.Application.main(Application.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:467)
	at java.lang.Thread.run(Thread.java:745)
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:467)
	at java.lang.Thread.run(Thread.java:745)
```

This is my `logback.xml` file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <timestamp key="date" datePattern="yyyyMMdd"/>

    <!-- The actual AwsLogsAppender (synchronous) -->
    <appender name="AWS_LOGS" class="ca.pjer.logback.AwsLogsAppender">
        <layout>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%level]  %logger{15}.%method\(line:%line\) : %m%n</pattern>
        </layout>
        <logGroupName>application-logs</logGroupName>
        <logStreamName>app-api-ci</logStreamName>

        <maxBatchSize>50</maxBatchSize>
        <maxFlushTimeMillis>5000</maxFlushTimeMillis>
        <maxBlockTimeMillis>0</maxBlockTimeMillis>
    </appender>

    <appender name="ASYNC_AWS_LOGS" class="ch.qos.logback.classic.AsyncAppender">
        <appender-ref ref="AWS_LOGS"/>
    </appender>

    <root level="INFO">
        <appender-ref ref="ASYNC_AWS_LOGS"/>
    </root>
</configuration>
```

As I said, if I remove these lines, the project is launched and the logs arrive to AWS CloudWatch Logs without problem:

```xml
        <maxBatchSize>50</maxBatchSize>
        <maxFlushTimeMillis>5000</maxFlushTimeMillis>
        <maxBlockTimeMillis>0</maxBlockTimeMillis>
```

We are using Spring Boot v1.3.1, and these are my Logback dependencies in the `pom.xml` file:

```xml
        <!-- Logback -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.3</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.2.3</version>
        </dependency>
        <!-- Logback + AWS CloudWatch Logs -->
        <dependency>
            <groupId>ca.pjer</groupId>
            <artifactId>logback-awslogs-appender</artifactId>
            <version>0.1.1</version>
        </dependency>
```

I got the same errors using `logback-awslogs-appender` versions 0.1.0 and 0.1.1.

The problem looks like these options are not recognized, because if I add an invalid option at the same level like this:

```xml
<iAmAnInvalidOption>0</iAmAnInvalidOption>
```

I get the same error:

```
ERROR in ch.qos.logback.core.joran.spi.Interpreter@14:23 - no applicable action for [iAmAnInvalidOption], current ElementPath  is [[configuration][appender][iAmAnInvalidOption]]
```

**Comment by pierredavidbelanger** [comment]
@mrsarm This error is related to a refactor we made to rename `maxBatchSize` into `maxBatchLogEvents ` (in #8).

Please, try to use the [latest 1.0.0-SNAPSHOT version](https://github.com/pierredavidbelanger/logback-awslogs-appender#pomxml), and be inspired by the [configuration options here](https://github.com/pierredavidbelanger/logback-awslogs-appender#more-configurations).

I will soon release the first stable release, 1.0.0, and those kind of refactor will follow the Semantic Versioning, so no surprises like this :)

**Comment by mrsarm** [comment]
It Worked ! Thanks
