### ISSUE TITLE
AWSCredentialsProviderChain log is null

### ISSUE THREAD

**Issue by barriem** [pierredavidbelanger/logback-awslogs-appender#17]
Hi Pierre,  

Firstly thanks for making this library, this is just what we need in our project.

We're seeing an issue where the `log` variable in the`AWSCredentialsProviderChain` is `null` at the point we attempt to execute our code.  I'm not sure how Logback initialisation works - but this seems like a circular dependency where initialising the logging framework expects a logger to be in scope? 

This is the closest version of the code I could find to `1.11.55` used in master - note the lines that are causing the issue:

https://github.com/aws/aws-sdk-java/blob/1.11.22/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWSCredentialsProviderChain.java#L119

https://github.com/aws/aws-sdk-java/blob/1.11.22/aws-java-sdk-core/src/main/java/com/amazonaws/auth/AWSCredentialsProviderChain.java#L126

The ultimate result of this is the `AWSCredentialsProviderChain.getCredentials()` call returns `null` which manifests itself in the following exception at runtime:

```10:32:04,453 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@53:16 - RuntimeException in Action for tag [appender] com.amazonaws.services.logs.model.AWSLogsException: Missing Authentication Token (Service: AWSLogs; Status Code: 400; Error Code: MissingAuthenticationTokenException; Request ID: e425147b-c889-11e8-b549-8991ee6adb84)
	at com.amazonaws.services.logs.model.AWSLogsException: Missing Authentication Token (Service: AWSLogs; Status Code: 400; Error Code: MissingAuthenticationTokenException; Request ID: e425147b-c889-11e8-b549-8991ee6adb84)
	at 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1632)
	at 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
	at 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at 	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at 	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at 	at com.amazonaws.services.logs.AWSLogsClient.doInvoke(AWSLogsClient.java:1685)
	at 	at com.amazonaws.services.logs.AWSLogsClient.invoke(AWSLogsClient.java:1661)
	at 	at com.amazonaws.services.logs.AWSLogsClient.createLogGroup(AWSLogsClient.java:464)
	at 	at ca.pjer.logback.AWSLogsStub.start(AWSLogsStub.java:41)
	at 	at ca.pjer.logback.AwsLogsAppender.start(AwsLogsAppender.java:133)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.end(AppenderAction.java:90)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callEndAction(Interpreter.java:309)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:193)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.endElement(Interpreter.java:179)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:62)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at 	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
	at 	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at 	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:645)
	at 	at com.amazonaws.auth.AWSCredentialsProviderChain.<clinit>(AWSCredentialsProviderChain.java:41)
	at 	at aws.Credential$.$anonfun$createCredentialProvider$1(types.scala:89)
	at 	at aws.AmazonClient.withClientConfiguration(AmazonClient.scala:34)
	at 	at aws.AmazonClient.create(AmazonClient.scala:54)
```

Have you seen this issue? is there something obvious we're missing from our configuration?  This is the configuration in our current `logback.xml`:

```
<appender name="AWS_LOGS" class="ca.pjer.logback.AwsLogsAppender">
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>DEBUG</level>
        </filter>

        <layout>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} %level [%thread] %logger{10} [%file:%line] %msg%n</pattern>
        </layout>

        <logGroupName>/radlab/bdec/catsalog</logGroupName>
        <logStreamName>${VPC_NAME}-debug-${timestamp}</logStreamName>
        <logRegion>eu-west-2</logRegion>
    </appender>
```

Thanks for your time,
Barrie

**Comment by pierredavidbelanger** [comment]
Do you have made your AWS credentials available to your app in a way that [DefaultAWSCredentialsProviderChain](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html) can find it ?

**Comment by barriem** [comment]
Hi Pierre, yes it's running on an EC2 instance with an instance profile assigned.  I forked your code and tried creating instances of the classes used by the `DefaultAWSCredentialsProivderChain` manually:

`EnvironmentVariableCredentialsProvider`, `SystemPropertiesCredentialsProvider`,  `ProfileCredentialsProvider` and `EC2ContainerCredentialsProviderWrapper`.  

The first 3 fail due to environment variables / system properties not being set.  The last one returns me a valid set of credentials.    When I added logic to wrap the `DefaultAWSCredentialsProviderChain.getCredentials()` call I saw from the stack trace that there is a `NullPointerException` when attempting to call `log.debug()..`

**Comment by barriem** [comment]
I fixed it by making the `AWSLogs` client initialisation lazy - have a look and see what you think:

https://github.com/barriem/logback-awslogs-appender/blob/lazyclient/src/main/java/ca/pjer/logback/AWSLogsStub.java#L24

**Comment by pierredavidbelanger** [comment]
This is interesting.

I appreciate you taking the time to provide those details.

I guess a temporary work around is to have a threshold for the root logger set to WARN or ERROR in order to NOT let the AWS code log into logback .. 

But I like your code too. Did you had to bump the requirements to use the `Lazy` thing ?
If not, send me a PR, I will have a look at it.

**Comment by barriem** [comment]
Hi Pierre, 

I added the `Lazy<T>` class to the codebase and uplifted the Java version and the AWS library version -  I got the `Lazy<T>` implementation from here: http://minborgsjavapot.blogspot.com/2016/01/be-lazy-with-java-8.html

However you can do the same thing in effect using Guava's `Suppliers.memoize` method:
https://google.github.io/guava/releases/22.0/api/docs/com/google/common/base/Suppliers.html#memoize-com.google.common.base.Supplier-

I can raise a PR if you like, but I need to write some unit tests first.  I'm easy as to whether you'd prefer to use Guava or a hand-rolled version of lazy initialisation?

Thanks,
Barrie

**Comment by pierredavidbelanger** [comment]
Your hand rolled version of `Lazy`  is more than good enough for me.

Also I am ok to bump the AWS library version.

I will gladly accept your PR.

**Comment by barriem** [comment]
thanks Pierre - PR raised here:  https://github.com/pierredavidbelanger/logback-awslogs-appender/pull/18
